"""added updated_at

Revision ID: 10b5aed4e074
Revises: 8065741ca17e
Create Date: 2026-08-16 00:34:33.542354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10b5aed4e074'
down_revision = '8065741ca17e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'updated_at')
    # ### end Alembic commands ###