"""added column next_attempt_at

Revision ID: 12570994dc89
Revises: 88de85e4cb07
Create Date: 2026-08-27 23:30:32.826258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12570994dc89'
down_revision = '88de85e4cb07'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'next_attempt_at')
    # ### end Alembic commands ###