"""added leases_expiry column in job table

Revision ID: 37bc647feac3
Revises: 410dcd919a21
Create Date: 2026-08-23 20:51:18.598925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37bc647feac3'
down_revision = '410dcd919a21'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'lease_expires_at')
    # ### end Alembic commands ###