"""added side effect table

Revision ID: 386ac96fd1e8
Revises: c6eab2899afc
Create Date: 2026-09-01 08:40:29.378493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '386ac96fd1e8'
down_revision = 'c6eab2899afc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('side_effects',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.BigInteger(), nullable=False),
    sa.Column('worker_id', sa.Text(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('side_effects')
    # ### end Alembic commands ###