"""added claimed_at in job table

Revision ID: 410dcd919a21
Revises: bed7fbd3882b
Create Date: 2026-08-23 20:14:14.590963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '410dcd919a21'
down_revision = 'bed7fbd3882b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'claimed_at')
    # ### end Alembic commands ###