"""added claim_generation(fencing)

Revision ID: 4beebaeb06dc
Revises: 6a472ccdd54c
Create Date: 2026-09-06 18:18:47.772914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4beebaeb06dc'
down_revision = '6a472ccdd54c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_executions', sa.Column('claim_generation', sa.BigInteger(), nullable=True))
    op.add_column('jobs', sa.Column('claim_generation', sa.BigInteger(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'claim_generation')
    op.drop_column('job_executions', 'claim_generation')
    # ### end Alembic commands ###