"""added enqueue idempotency and unique constraint

Revision ID: 6a472ccdd54c
Revises: e86d0ef9cc89
Create Date: 2026-09-03 17:21:28.656136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a472ccdd54c'
down_revision = 'e86d0ef9cc89'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('idempotency_key', sa.Text(), nullable=True))
    op.add_column('jobs', sa.Column('request_fingerprint', sa.Text(), nullable=True))
    op.create_unique_constraint('uq_jobs_idempotency_key', 'jobs', ['idempotency_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_jobs_idempotency_key', 'jobs', type_='unique')
    op.drop_column('jobs', 'request_fingerprint')
    op.drop_column('jobs', 'idempotency_key')
    # ### end Alembic commands ###