"""added completed_at and last_error

Revision ID: 87990f3ddcb5
Revises: 4beebaeb06dc
Create Date: 2026-09-08 23:44:19.160812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87990f3ddcb5'
down_revision = '4beebaeb06dc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('jobs', sa.Column('last_error', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'last_error')
    op.drop_column('jobs', 'completed_at')
    # ### end Alembic commands ###