"""added effect_key column

Revision ID: e86d0ef9cc89
Revises: 386ac96fd1e8
Create Date: 2026-09-01 19:26:54.493835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e86d0ef9cc89'
down_revision = '386ac96fd1e8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('side_effects', sa.Column('effect_key', sa.Text(), nullable=True))
    op.create_unique_constraint('uq_side_effects_effect_key', 'side_effects', ['effect_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_side_effects_effect_key', 'side_effects', type_='unique')
    op.drop_column('side_effects', 'effect_key')
    # ### end Alembic commands ###